cluster.name: wayen
node.name: {{ pillar.get('elasticsearch.node.name')}}
path.data: /var/elasticsearch/data
path.logs: /var/elasticsearch/logs
bootstrap.memory_lock: false
network.host: 0.0.0.0
http.port: 9200
